name: climaax_snow

channels:
    - conda-forge

dependencies:
    - python=3.11
    - pip
    - jupyterlab=4.2.3
    - jupyterlab-myst=2.4.2
    - ipykernel=6.29.5
    - cdsapi=0.7.0
    - pooch=1.8.2
    - numpy=1.26.4
    - xarray=2024.6.0
    - dask=2024.7.0
    - xesmf=0.8.6
    - rioxarray=0.15.7
    - pyproj=3.6.1
    - matplotlib=3.8.4
    - cartopy=0.23.0
    - netcdf4=1.7.1
